### ISSUE TITLE
nagiostats can deliver correct data directly

### ISSUE THREAD

**Issue by klaernie** [matteocorti/check_nagios_latency#1]
According to the nagiostats help page we could skip manual parsing of the nagiostats output and also drop the external dependency on `bc` by using nagiostats `--mrtg` option:

``` sh
$ nagiostats | grep "Active Service Latency" |cut -f3 -d'/' | awk '{print $1}'
0.425
$ nagiostats --mrtg -d AVGACTSVCLAT
425
```

As this option outputs milliseconds we can use integer arithmetic instead of using floats, by which we can switch from using `bc` to using the shell's internal calculations.

**Comment by klaernie** [comment]
if you like I can send a PR implementing this.

Furthermore it would be possible to generalize the field being checked, so it can check other fields (I am thinking about host checks, each of their execution time and the maximum values)

**Comment by matteocorti** [comment]
Sure why not thanks!
